---
- name: Check if Jenkins is listening on port 8080
  wait_for:
    port: 8080
    timeout: 5
  register: jenkins_port_check
  ignore_errors: true

- name: Display Jenkins status
  debug:
    msg: "Jenkins is up and running on port 8080"
  when: jenkins_port_check.state is defined and jenkins_port_check.state == "started"

- name: Warn if Jenkins is not running
  debug:
    msg: "Warning: Jenkins is not responding on port 8080!"
  when: jenkins_port_check.state is not defined or jenkins_port_check.state != "started"
