apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-a-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospital-a-service
  template:
    metadata:
      labels:
        app: hospital-a-service
    spec:
      containers:
      - name: hospital-a-service
        image: health-bridge/hospital-a-service:1.0
        env:
        - name: EUREKA_SERVER_URL
          value: "http://discovery-server:9095/eureka/"
        - name: HOSPITAL_A_DB_URL
          value: "jdbc:postgresql://postgres-db:5432/fhir_main"
        - name: APP_CORS_ALLOWED_ORIGIN_PATTERNS
          value: "*"
        ports:
        - containerPort: 9097
---
apiVersion: v1
kind: Service
metadata:
  name: hospital-a-service
spec:
  selector:
    app: hospital-a-service
  ports:
    - protocol: TCP
      port: 9097
      targetPort: 9097
  type: ClusterIP
