spring.application.name=hie-fhir-exchange-service
server.port=${SERVER_PORT:8086}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

spring.datasource.jdbc-url=${HIE_SUPPORT_DB_URL:jdbc:postgresql://localhost:5432/fhir_main}
spring.datasource.username=${HIE_SUPPORT_DB_USERNAME:fhir_user}
spring.datasource.password=${HIE_SUPPORT_DB_PASSWORD:fhir_pass}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=${JPA_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}

app.mongo.hospital-b.uri=${HOSPITAL_B_MONGO_URI:mongodb://localhost:27017}
app.mongo.hospital-b.database=${HOSPITAL_B_MONGO_DATABASE:hospital_b}
app.mongo.hospital-b.auto-index-creation=${HOSPITAL_B_MONGO_AUTO_INDEX_CREATION:true}

auth.identity.base-url=${AUTH_IDENTITY_BASE_URL:http://localhost:8081}
consent.service.base-url=${CONSENT_SERVICE_BASE_URL:http://localhost:8082}
hospital-a.service.base-url=${HOSPITAL_A_SERVICE_BASE_URL:http://localhost:8083}
hospital-b.service.base-url=${HOSPITAL_B_SERVICE_BASE_URL:http://localhost:8084}
app.cors.allowed-origin-patterns=${CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost:5173,http://localhost:5174,http://localhost:5175}
jwt.secret=${JWT_SECRET:change-me-to-a-256-bit-base64-secret-in-prod-at-least-32-chars}
jwt.access-token-expiry-seconds=${JWT_ACCESS_TOKEN_EXPIRY_SECONDS:3600}
jwt.refresh-token-expiry-seconds=${JWT_REFRESH_TOKEN_EXPIRY_SECONDS:604800}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.info.env.enabled=true
info.app.name=hie-fhir-exchange-service
info.app.phase=phase-2-skeleton
