spring.application.name=api-gateway-service
server.port=${SERVER_PORT:9091}

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:9095/eureka/}
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.routes[0].id=auth-identity-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://auth-identity-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**,/identity/**,/hospitals/**

spring.cloud.gateway.server.webflux.routes[1].id=consent-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://consent-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/consent/**

spring.cloud.gateway.server.webflux.routes[2].id=hospital-a-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://hospital-a-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/hospitalA/op-consult/**

spring.cloud.gateway.server.webflux.routes[3].id=hospital-b-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://hospital-b-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/hospitalB/op-consult/**

spring.cloud.gateway.server.webflux.routes[4].id=hie-fhir-exchange-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://hie-fhir-exchange-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/hie/**,/doctor/patients/**,/patient/consultations/**

spring.cloud.gateway.server.webflux.routes[5].id=notification-audit-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://notification-audit-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/patient/audit/**,/hospitalA/notifications/**,/hospitalB/notifications/**,/admin/transfers

spring.cloud.gateway.server.webflux.routes[6].id=admin-reporting-service
spring.cloud.gateway.server.webflux.routes[6].uri=lb://admin-reporting-service
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/admin/audit-logs,/admin/system-health

spring.cloud.gateway.server.webflux.routes[7].id=auth-identity-admin-service
spring.cloud.gateway.server.webflux.routes[7].uri=lb://auth-identity-service
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/admin/users/**

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.probes.enabled=true
management.info.env.enabled=true
info.app.name=api-gateway-service
info.app.phase=phase-2-skeleton
