# Kubernetes profile
# Service names assume in-cluster DNS via ClusterIP services.

spring.datasource.fhir-main.jdbc-url=jdbc:postgresql://fhir-main-db:5432/fhir_main
spring.datasource.hospital-a.jdbc-url=jdbc:postgresql://hospital-a-db:5432/hospital_a_db
app.mongo.hospital-b.uri=mongodb://hospital-b-mongo:27017
app.mongo.hospital-b.database=hospital_b

app.cors.allowed-origin-patterns=http://healthbridge.local,http://hospital-a.healthbridge.local,http://hospital-b.healthbridge.local

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
