# Docker profile
# Service hostnames assume a future docker-compose network.

spring.datasource.fhir-main.jdbc-url=jdbc:postgresql://postgres-main:5432/fhir_main
spring.datasource.hospital-a.jdbc-url=jdbc:postgresql://postgres-hospital-a:5432/hospital_a_db
app.mongo.hospital-b.uri=mongodb://mongo-hospital-b:27017
app.mongo.hospital-b.database=hospital_b

app.cors.allowed-origin-patterns=http://localhost:8080,http://localhost:8081,http://localhost:8082

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
